title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.1358754
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#d73030'
    - '#f0f0f0'
    - '#dddddd'
    - '#f39b9b'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74761061-1
  facebook: null
name: theleicastreet
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.90836
layout_spectrum: 0.04431
