name: theleicastreet
favicon: null
layout_spectrum: 0.28709
typography_spectrum: 0.8888292
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74761061-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d73030'
    - '#f0f0f0'
    - '#dddddd'
    - '#f39b9b'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
