title: The Leica Street
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.1875
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#d73030'
    - '#f0f0f0'
    - '#dddddd'
    - '#f39b9b'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74761061-1
  facebook: null
name: The Leica Street
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.90836
layout_spectrum: 0.3528464
