favicon: null
name: theleicastreet
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0.9923725400585681
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 1
typography_spectrum: 0.06849
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3345864
analytics:
  twitter: null
  google: null
  facebook: null
