title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4003759
  brandStrength: 0.75
  lightness: 0.8753133
  brandColors:
    - '#ffffff'
    - '#d73030'
    - '#f0f0f0'
    - '#dddddd'
    - '#f39b9b'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: theleicastreet
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8888292
layout_spectrum: 0.34079
